/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Clases.vistas;

import Clases.dao.InspeccionFitosanitariaDAO;
import Clases.modelo.InspeccionFitosanitaria;
import Clases.libreria.Dashboard;
import javax.swing.JOptionPane;
import Clases.vistas.UpInspeccionFitosanitaria;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricar
 */
public class GestionInspeccionesFitosanitarias extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    private String nombreRol;

    public GestionInspeccionesFitosanitarias(String nombreRol) {
        this.nombreRol = nombreRol;
        initComponents();
        LoadInspeccionFitosanitaria();
        aplicarPermisos();
    }

    public GestionInspeccionesFitosanitarias() {
        this("Consulta"); // Rol por defecto si no envían nombreRol
    }

    private void aplicarPermisos() {

        switch (nombreRol) {

            case "Administrador ICA":
            case "Asistente Tecnico":

                btnNuevaInspeccion.setVisible(true);
                btnEditar.setVisible(true);
                btnBorrar.setVisible(true);
                break;

            case "Productor":
                btnNuevaInspeccion.setVisible(false);
                btnEditar.setVisible(false);
                btnBorrar.setVisible(false);
                jLabel2.setVisible(false);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                jLabel9.setVisible(false);
                jLabel10.setVisible(false);

                break;

            default:
                btnNuevaInspeccion.setVisible(false);
                btnEditar.setVisible(false);
                btnBorrar.setVisible(false);
                break;
        }
    }

    private void LoadInspeccionFitosanitaria() {
        try {
            InspeccionFitosanitariaDAO dao = new InspeccionFitosanitariaDAO();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // limpia la tabla

            dao.listarTodos().forEach((u) -> {
                model.addRow(new Object[]{
                    u.getIdInspeccion(),
                    u.getCantidadPlantas(),
                    u.getEstadoFenologico(),
                    u.getFecInspeccion(),
                    u.getObservaciones(),
                    u.getNombreUsuario(),
                    u.getNombreLugarProduccion(),
                    u.getNumeroLote(),});

            });

            // Ocultar la primera columna (ID)
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(0).setWidth(0);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnNuevaInspeccion = new javax.swing.JButton();
        btnbuscar = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(770, 480));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 430));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Gestión de Inspecciones:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Cantidad Plantas", "Estado Fenologico", "Fecha de Inspección", "Observaciones", "Asistente tecnico", "Lugar de Producción", "Numero de lote"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
        }

        btnNuevaInspeccion.setText("+ Nueva Inspección");
        btnNuevaInspeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaInspeccionActionPerformed(evt);
            }
        });

        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Para poder añadir las plagas que evidenciaste durante cierta inspección, primero debes tener creada la inspección. Para crear nuevas");

        jLabel7.setText("inspeecciones, presiona el botón \"+ Nueva Inspeccion\"; se abrirá una nueva ventana e ingresa todos los datos solicitados.");

        jLabel8.setText("Posteriormente, podrás presionar el botón \"Editar\", en donde se abrirá una nueva ventana. Allí podrás gestionar las plagas evidenciadas,");

        jLabel9.setText("es decir, podrás añadir nuevas plagas e ingresar los datos de la cantidad de plantas infestadas (plaga por plaga); y podrás editar o eliminar");

        jLabel10.setText("las plagas ya añadidas. Igualmente, podrás modificar los datos correspondientes a la inspección.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevaInspeccion)
                .addGap(50, 50, 50)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar)
                    .addComponent(btnEditar)
                    .addComponent(btnNuevaInspeccion))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaInspeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaInspeccionActionPerformed
        Dashboard.ShowJPanel(new UpInspeccionFitosanitaria(nombreRol));
    }//GEN-LAST:event_btnNuevaInspeccionActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        InspeccionFitosanitariaDAO dao = new InspeccionFitosanitariaDAO();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        int[] selected = jTable1.getSelectedRows();
        if (selected.length < 1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar uno o más Inspecciones para eliminar.", "AVISO", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de eliminar las inspecciones seleccionadas?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion != JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Eliminación cancelada por el usuario.");
            return;
        }

        int eliminados = 0;
        java.util.Arrays.sort(selected);

        // 🔹 Recorremos de atrás hacia adelante para evitar conflictos de índice
        for (int idx = selected.length - 1; idx >= 0; idx--) {
            int row = selected[idx];
            try {
                Object valorCelda = jTable1.getValueAt(row, 0);

                if (valorCelda == null) {
                    JOptionPane.showMessageDialog(
                            this,
                            "La fila " + (row + 1) + " no tiene un ID válido (columna vacía).",
                            "Advertencia",
                            JOptionPane.WARNING_MESSAGE
                    );
                    continue;
                }

                String idInspeccionFitosanitaria = valorCelda.toString();

                boolean ok = dao.eliminar(idInspeccionFitosanitaria);
                if (ok) {
                    model.removeRow(row);
                    eliminados++;
                } else {
                    JOptionPane.showMessageDialog(
                            this,
                            "No se pudo eliminar la inspección con ID: " + idInspeccionFitosanitaria,
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(
                        this,
                        "Error inesperado al eliminar la fila " + (row + 1) + ": " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }

        if (eliminados > 0) {
            JOptionPane.showMessageDialog(this, eliminados + " Inspeccione(s) eliminadas correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No se eliminó ninguna inspección.");
        }

    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una inspección de la tabla para editarlo.");
            return;
        }

        // Supongamos que la columna 0 tiene el número de identificación
        String idInspeccionFitosanitaria = jTable1.getValueAt(fila, 0).toString();
        String lugarInspec = jTable1.getValueAt(fila, 6).toString();
        String loteLugar = jTable1.getValueAt(fila, 7).toString();

        // Buscar la Inspección en la BD
        try {
            Clases.dao.InspeccionFitosanitariaDAO buscarId = new Clases.dao.InspeccionFitosanitariaDAO();
            Clases.modelo.InspeccionFitosanitaria inspeccionfitosanitaria = buscarId.buscarPorId(idInspeccionFitosanitaria);

            if (inspeccionfitosanitaria != null) {
                // Crear el panel EditInspeccionFitosanitaria y pasarle la inspeccion
                inspeccionfitosanitaria.setNombreLugarProduccion(lugarInspec);
                EditInspeccionFitosanitaria panelEditar = new EditInspeccionFitosanitaria(inspeccionfitosanitaria,nombreRol);

                // Mostrar el panel en el Dashboard
                Dashboard.ShowJPanel(panelEditar);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró la inspección seleccionado.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al obtener la inspección: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNuevaInspeccion;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField btnbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
