/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Clases.vistas;

import Clases.dao.UsuarioDAO;
import Clases.modelo.Usuarios;
import Clases.libreria.Dashboard;
import javax.swing.JOptionPane;
import Clases.vistas.UpUsers;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricar
 */
public class GestionPredios extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public GestionPredios() {
        initComponents();
        LoadUsers();
    }

    private void LoadUsers() {
        try {
            UsuarioDAO dao = new UsuarioDAO();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            // Limpiar la tabla antes de cargar nuevos datos
            model.setRowCount(0);

            // Llenar el modelo con los datos
            dao.listarTodos().forEach((u) -> {
                model.addRow(new Object[]{
                    u.getIdUsuario(), // 🔹 ID oculto
                    u.getNumIdentificacion(),
                    u.getNombres(),
                    u.getApellidos(),
                    u.getTelefono(),
                    u.getCorreoElectronico(),
                    u.getNomRol()
                });
            });

            // 🔹 Ocultar la primera columna (id_usuario)
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(0).setWidth(0);

        } catch (Exception e) {
            System.out.println("Error al cargar usuarios: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnbuscar = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Gestión de Predios:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Identificación", "Nombres", "Apellidos", "Teléfono", "Correo Electronico", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("+ Nuevo usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(40, 40, 40)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnEditar)
                    .addComponent(btnBorrar))
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Dashboard.ShowJPanel(new UpUsers());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        UsuarioDAO dao = new UsuarioDAO();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        int[] selected = jTable1.getSelectedRows();
        if (selected.length < 1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Debes seleccionar uno o más usuarios para eliminar.",
                    "AVISO",
                    JOptionPane.WARNING_MESSAGE
            );
        } else {
            int confirmacion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Está seguro de eliminar los usuarios seleccionados?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE
            );

            if (confirmacion == JOptionPane.YES_OPTION) {
                int eliminados = 0;
                // Iterar de atrás hacia adelante para evitar desajustes al eliminar filas
                java.util.Arrays.sort(selected);
                for (int idx = selected.length - 1; idx >= 0; idx--) {
                    int row = selected[idx];
                    try {
                        // Se asume que la primera columna (0) contiene el id_usuario oculto
                        String idUsuario = jTable1.getValueAt(row, 0).toString();
                        boolean ok = dao.eliminar(idUsuario);

                        if (ok) {
                            model.removeRow(row);
                            eliminados++;
                        } else {
                            JOptionPane.showMessageDialog(
                                    this,
                                    "No se pudo eliminar el usuario con ID: " + idUsuario,
                                    "Error",
                                    JOptionPane.ERROR_MESSAGE
                            );
                        }

                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(
                                this,
                                "Error inesperado al eliminar el usuario en la fila " + row + ": " + e.getMessage(),
                                "Error",
                                JOptionPane.ERROR_MESSAGE
                        );
                    }
                }

                if (eliminados > 0) {
                    JOptionPane.showMessageDialog(
                            this,
                            eliminados + " usuario(s) eliminado(s) correctamente."
                    );
                } else {
                    JOptionPane.showMessageDialog(
                            this,
                            "No se eliminó ningún usuario."
                    );
                }

            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Eliminación cancelada por el usuario."
                );
            }
        }

    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un usuario de la tabla.");
            return;
        }

        // Supongamos que la columna 0 tiene el número de identificación
        String idUser = jTable1.getValueAt(fila, 0).toString();

        // Buscar el usuario en la BD
        try {
            // Buscar el usuario en la BD
            Clases.dao.UsuarioDAO buscarId = new Clases.dao.UsuarioDAO();
            Clases.modelo.Usuarios usuario = buscarId.getUserById(idUser);

            if (usuario != null) {
                // Crear el panel EditUsers y pasarle el usuario
                EditUsers panelEditar = new EditUsers();
                panelEditar.setUsuario(usuario);

                // Mostrar el panel en el Dashboard
                Dashboard.ShowJPanel(panelEditar);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el usuario seleccionado.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al obtener el usuario: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField btnbuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
