/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Clases.vistas;

import Clases.dao.LugarProduccionDAO;
import Clases.modelo.LugarProduccion;
import Clases.libreria.Dashboard;
import javax.swing.JOptionPane;
import Clases.vistas.UpLugarProduccion;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ricar
 */
public class GestionLugaresProduccion extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public GestionLugaresProduccion() {
        initComponents();
        LoadLugarProduccion();
    }

    private void LoadLugarProduccion() {
        try {
            LugarProduccionDAO dao = new LugarProduccionDAO();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // limpia la tabla

            dao.listarTodos().forEach((u) -> {
                model.addRow(new Object[]{
                    u.getIdLugarProduccion(), 
                    u.getNomLugarProduccion(),
                    u.getNroRegistroICA(),
                    u.getNombreUsuario(),
                });
            });

            // Ocultar la primera columna (ID)
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(0).setWidth(0);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnLugarProduccion = new javax.swing.JButton();
        btnbuscar = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Gestión de Lugares de Producción:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre", "Codigo ICA", "Productor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
        }

        btnLugarProduccion.setText("+ Nuevo Lugar de Producción");
        btnLugarProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLugarProduccionActionPerformed(evt);
            }
        });

        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLugarProduccion)
                .addGap(40, 40, 40)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLugarProduccion)
                    .addComponent(btnEditar)
                    .addComponent(btnBorrar))
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLugarProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLugarProduccionActionPerformed
        Dashboard.ShowJPanel(new UpLugarProduccion());
    }//GEN-LAST:event_btnLugarProduccionActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        LugarProduccionDAO dao = new LugarProduccionDAO();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        int[] selected = jTable1.getSelectedRows();
        if (selected.length < 1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar uno o más Lugares de produccion para eliminar.", "AVISO", JOptionPane.WARNING_MESSAGE);
        } else {
            int confirmacion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Está seguro de eliminar los Lugares de produccion seleccionados?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE
            );

            if (confirmacion == JOptionPane.YES_OPTION) {
                int eliminados = 0;
                // Iterar de atrás hacia adelante para evitar desajustes de índices al remover filas
                java.util.Arrays.sort(selected);
                for (int idx = selected.length - 1; idx >= 0; idx--) {
                    int row = selected[idx];
                    try {
                        String idLugarProduccion = jTable1.getValueAt(row, 0).toString();
                        boolean ok = dao.eliminar(idLugarProduccion);
                        if (ok) {
                            model.removeRow(row);
                            eliminados++;
                        } else {
                            // No se eliminó: informar al usuario por cada fila fallida (opcional)
                            JOptionPane.showMessageDialog(
                                    this,
                                    "No se pudo eliminar el lugar de produccion con ID: " + idLugarProduccion,
                                    "Error",
                                    JOptionPane.ERROR_MESSAGE
                            );
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(
                                this,
                                "Error inesperado al eliminar la fila " + row + ": " + e.getMessage(),
                                "Error",
                                JOptionPane.ERROR_MESSAGE
                        );
                    }
                }

                if (eliminados > 0) {
                    JOptionPane.showMessageDialog(this, eliminados + " Lugar(s) de produccion eliminados correctamente.");
                } else {
                    JOptionPane.showMessageDialog(this, "No se eliminó ningún lugar de produccion.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Eliminación cancelada por el usuario.");
            }
        }

    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un lugar de producción de la tabla para editarlo.");
            return;
        }

        // Supongamos que la columna 0 tiene el número de identificación
        String idLugarProduccion = jTable1.getValueAt(fila, 0).toString();

        // Buscar el Lugar de produccion en la BD
        try {
            // Buscar el lugar de produccion en la BD
            Clases.dao.LugarProduccionDAO buscarId = new Clases.dao.LugarProduccionDAO();
            Clases.modelo.LugarProduccion lugarproduccion = buscarId.buscarPorId(idLugarProduccion);

            if (lugarproduccion != null) {
                // Crear el panel EditLugarProduccion y pasarle el lugar de produccion
                EditLugarProduccion panelEditar = new EditLugarProduccion();
                panelEditar.setLugarProduccion(lugarproduccion);

                // Mostrar el panel en el Dashboard
                Dashboard.ShowJPanel(panelEditar);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el municipio seleccionado.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al obtener el municipio: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLugarProduccion;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField btnbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
