/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Clases.vistas;

import Clases.dao.LoteDAO;
import Clases.modelo.Lote;
import Clases.libreria.Dashboard;
import javax.swing.JOptionPane;
import Clases.vistas.UpLote;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricar
 */
public class GestionLotes extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    private String nombreRol;

    public GestionLotes(String nombreRol) {
        this.nombreRol = nombreRol;
        initComponents();
        LoadLote();
        aplicarPermisos();

    }

    public GestionLotes() {
        this("Consulta"); // Rol por defecto si no envían nombreRol
    }

    private void aplicarPermisos() {

        switch (nombreRol) {

            case "Administrador ICA":
            case "Productor":
                btnNuevoLote.setVisible(true);
                btnEditar.setVisible(true);
                btnBorrar.setVisible(true);
                break;

            case "Asistente Tecnico":
                btnNuevoLote.setVisible(false);
                btnEditar.setVisible(false);
                btnBorrar.setVisible(false);
                break;

            default:
                btnNuevoLote.setVisible(false);
                btnEditar.setVisible(false);
                btnBorrar.setVisible(false);
                break;
        }
    }

    private void LoadLote() {
        try {
            LoteDAO dao = new LoteDAO();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // limpia la tabla

            dao.listarTodos().forEach((u) -> {
                model.addRow(new Object[]{
                    u.getIdLote(),
                    u.getNumero(),
                    u.getAreaTotal(),
                    u.getFecSiembra(),
                    u.getFecEliminacion(),
                    u.getNombreVariedad(),
                    u.getNombreLugarProduccion(),});

            });

            // Ocultar la primera columna (ID)
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(0).setWidth(0);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnNuevoLote = new javax.swing.JButton();
        btnbuscar = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Gestión de Lotes:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Numero", "Area Total", "Fecha de siembra", "Fecha de eliminacion", "Variedad Vegetal", "Lugar de Produccion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
        }

        btnNuevoLote.setText("+ Nuevo Lote");
        btnNuevoLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoLoteActionPerformed(evt);
            }
        });

        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevoLote)
                .addGap(40, 40, 40)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoLote)
                    .addComponent(btnEditar)
                    .addComponent(btnBorrar))
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoLoteActionPerformed
        Dashboard.ShowJPanel(new UpLote());
    }//GEN-LAST:event_btnNuevoLoteActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        LoteDAO dao = new LoteDAO();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        int[] selected = jTable1.getSelectedRows();
        if (selected.length < 1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar uno o más Lotes para eliminar.", "AVISO", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de eliminar los lotes seleccionadas?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion != JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Eliminación cancelada por el usuario.");
            return;
        }

        int eliminados = 0;
        java.util.Arrays.sort(selected);

        // 🔹 Recorremos de atrás hacia adelante para evitar conflictos de índice
        for (int idx = selected.length - 1; idx >= 0; idx--) {
            int row = selected[idx];
            try {
                Object valorCelda = jTable1.getValueAt(row, 0);

                if (valorCelda == null) {
                    JOptionPane.showMessageDialog(
                            this,
                            "La fila " + (row + 1) + " no tiene un ID válido (columna vacía).",
                            "Advertencia",
                            JOptionPane.WARNING_MESSAGE
                    );
                    continue;
                }

                String idLote = valorCelda.toString();

                boolean ok = dao.eliminar(idLote);
                if (ok) {
                    model.removeRow(row);
                    eliminados++;
                } else {
                    JOptionPane.showMessageDialog(
                            this,
                            "No se pudo eliminar el lote con ID: " + idLote,
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(
                        this,
                        "Error inesperado al eliminar la fila " + (row + 1) + ": " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }

        if (eliminados > 0) {
            JOptionPane.showMessageDialog(this, eliminados + " Lote(s) eliminadas correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No se eliminó ninguna lote.");
        }

    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un lote de la tabla para editarlo.");
            return;
        }

        // Supongamos que la columna 0 tiene el número de identificación
        String idLote = jTable1.getValueAt(fila, 0).toString();

        // Buscar el Lote en la BD
        try {
            // Buscar el Lote en la BD
            Clases.dao.LoteDAO buscarId = new Clases.dao.LoteDAO();
            Clases.modelo.Lote lote = buscarId.buscarPorId(idLote);

            if (lote != null) {
                // Crear el panel EditLote y pasarle el lote
                EditLote panelEditar = new EditLote();
                panelEditar.setLote(lote);

                // Mostrar el panel en el Dashboard
                Dashboard.ShowJPanel(panelEditar);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró la lote seleccionado.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al obtener el lote: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNuevoLote;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField btnbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
