/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Clases.vistas;

import Clases.dao.InspeccionPlagaDAO;
import Clases.dao.PlagaDAO;
import Clases.libreria.Dashboard;
import Clases.modelo.InspeccionFitosanitaria;
import Clases.modelo.InspeccionPlaga;
import javax.swing.JOptionPane;

/**
 *
 * @author ricar
 */
public class UpInspeccionPlaga extends javax.swing.JPanel {
    
    private String IdInspeccion;
    private String idPlaga;
    private InspeccionFitosanitaria inspeccionActual;
    private String nomPlaga;

    public UpInspeccionPlaga(InspeccionFitosanitaria inspeccionPlaga) {
        initComponents();
        inspeccionActual = inspeccionPlaga;
        IdInspeccion = inspeccionPlaga.getIdInspeccion();
        lblNombreLugar.setText(inspeccionPlaga.getNombreLugarProduccion());
        lblNumLote.setText(inspeccionPlaga.getNumeroLote());
        lblFechaInspec.setText(inspeccionPlaga.getFecInspeccion().toString());
        cargarPlagasNoAsociadas();
    }
    
    private void cargarPlagasNoAsociadas() {
        PlagaDAO dao = new PlagaDAO();

        listPlagas.removeAll();

        dao.listarNoAsociadasAInspeccion(IdInspeccion).forEach((p) -> {
            listPlagas.add(
                p.getIdPlaga() + " - " +
                p.getNombreComun()+ " (" + p.getNomEspecie()+ ")"
            );
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardarPlagasInspec = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        listPlagas = new java.awt.List();
        lblNombreLugar = new javax.swing.JLabel();
        lblNumLote = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblFechaInspec = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 430));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 430));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Selecciona la plaga que se evidenció durante la inspección en:");

        jLabel2.setText("A continuación, se presenta una lista de las plagas disponibles. Selecciona una a la vez para continuar con el siguiente paso:");

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardarPlagasInspec.setBackground(new java.awt.Color(51, 153, 0));
        btnGuardarPlagasInspec.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardarPlagasInspec.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarPlagasInspec.setText("Seleccionar y continuar");
        btnGuardarPlagasInspec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPlagasInspecActionPerformed(evt);
            }
        });

        jLabel3.setText("En el siguiente paso, deberás indicar la \"cantidad de plantas afectadas\"; el software calculará automáticamente el porcentaje de");

        jLabel4.setText("infestación. Recuerda que el número de plantas afectadas debe ser menor o igual al total de cantidad de plantas");

        listPlagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPlagasActionPerformed(evt);
            }
        });

        lblNombreLugar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreLugar.setForeground(new java.awt.Color(0, 153, 51));
        lblNombreLugar.setText("NombreLugarPr");

        lblNumLote.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumLote.setForeground(new java.awt.Color(0, 153, 51));
        lblNumLote.setText("NumeroLote");

        jLabel5.setText("Lugar de producción:");

        jLabel6.setText("Número de Lote:");

        jLabel7.setText("Fecha inspección:");

        lblFechaInspec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaInspec.setForeground(new java.awt.Color(0, 153, 51));
        lblFechaInspec.setText("FechaInspec");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarPlagasInspec))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombreLugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addComponent(lblNumLote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblFechaInspec, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listPlagas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreLugar)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(lblFechaInspec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumLote)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listPlagas, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardarPlagasInspec))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarPlagasInspecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPlagasInspecActionPerformed
        String seleccion = listPlagas.getSelectedItem();
        
        if (seleccion == null) {
            JOptionPane.showMessageDialog(this,
                "Debes seleccionar una plaga antes de continuar.",
                "Sin plaga seleccionada",
                JOptionPane.WARNING_MESSAGE);
            return; // no continúa si falta información
        }
        try {
            InspeccionPlagaDAO plagaDao = new InspeccionPlagaDAO();
            // item viene con formato "12 - NombreCientífico (NombreComún)"
            idPlaga = seleccion.split(" - ")[0].trim();
            nomPlaga = seleccion.split(" - ")[1].trim();
            plagaDao.insertarInspecPlaga(IdInspeccion, idPlaga);
            JOptionPane.showMessageDialog(this, 
                "Plaga asociada correctamente a la inspección fitosanitaria");

            // Opcional: limpiar selección
            listPlagas.deselect(listPlagas.getSelectedIndex());

            // Opcional: recargar lista para desaparecer las plagas ya asociadas
            cargarPlagasNoAsociadas();
            InspeccionPlaga plaga = plagaDao.obtenerInspecPlaga(IdInspeccion, idPlaga);
            Dashboard.ShowJPanel(new UpInspeccionPlagaExtra(false, inspeccionActual, idPlaga, nomPlaga, plaga.getCantidadPlantasInfestadas()));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al guardar: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarPlagasInspecActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Dashboard.ShowJPanel(new GestionInspeccionesFitosanitarias());
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void listPlagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPlagasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listPlagasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardarPlagasInspec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFechaInspec;
    private javax.swing.JLabel lblNombreLugar;
    private javax.swing.JLabel lblNumLote;
    private java.awt.List listPlagas;
    // End of variables declaration//GEN-END:variables
}
