/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Clases.vistas;

import Clases.dao.InspeccionPlagaDAO;
import Clases.dao.PlagaDAO;
import Clases.libreria.Dashboard;
import Clases.modelo.InspeccionFitosanitaria;
import Clases.modelo.InspeccionPlaga;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricar
 */
public class UpInspeccionPlagaUpdate extends javax.swing.JPanel {
    
    private String IdInspeccion;
    private String idPlaga;
    private InspeccionFitosanitaria inspeccionActual;
    private String nomPlaga;

    public UpInspeccionPlagaUpdate(InspeccionFitosanitaria inspeccionPlaga) {
        initComponents();
        inspeccionActual = inspeccionPlaga;
        IdInspeccion = inspeccionPlaga.getIdInspeccion();
        lblNombreLugar.setText(inspeccionPlaga.getNombreLugarProduccion());
        lblNumLote.setText(inspeccionPlaga.getNumeroLote());
        lblFechaInspec.setText(inspeccionPlaga.getFecInspeccion().toString());
        LoadPlagasAsociadas();
    }
    
    private void LoadPlagasAsociadas() {
        try {
            InspeccionPlagaDAO dao = new InspeccionPlagaDAO();
            DefaultTableModel model = (DefaultTableModel) tblPlagasAsociadas.getModel();
            model.setRowCount(0); // limpia la tabla

            // Llamamos al nuevo método DAO que devuelve la lista de objetos
            dao.listarPlagasInspeccion(IdInspeccion).forEach((plaga) -> {
                model.addRow(new Object[]{
                    plaga.getIdPlaga(),
                    plaga.getNomEspecie(),             // Muestra el nombre
                    plaga.getCantidadPlantasInfestadas(),
                    plaga.getPorcentajeInfestacion()
                });
            });
            
            // 🔹 Ocultar la primera columna (id_usuario)
            tblPlagasAsociadas.getColumnModel().getColumn(0).setMinWidth(0);
            tblPlagasAsociadas.getColumnModel().getColumn(0).setMaxWidth(0);
            tblPlagasAsociadas.getColumnModel().getColumn(0).setWidth(0);
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla de plagas: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnEliminarPlaga = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNombreLugar = new javax.swing.JLabel();
        lblNumLote = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlagasAsociadas = new javax.swing.JTable();
        btnEditarPlaga = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblFechaInspec = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(770, 430));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 430));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Selecciona la plaga que deseas modificar o eliminar, la cual está asociada a la inspección realizada en:");

        jLabel2.setText("A continuación, se presentan las plagas que ya están asociadas. Para seleccionar varios registros mantenga presionada la tecla \"Ctrl\":");

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEliminarPlaga.setText("Eliminar plaga(s) de la inspección");
        btnEliminarPlaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPlagaActionPerformed(evt);
            }
        });

        jLabel3.setText("Presiona \"Editar información de plaga\" si deseas modificar la cantidad de plantas infestadas de la plaga seleccionada. El porcentaje de");

        jLabel4.setText("infestación no se modifica, puesto que se calcula automáticamente).");

        lblNombreLugar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreLugar.setForeground(new java.awt.Color(0, 153, 51));
        lblNombreLugar.setText("NombreLugarPr");

        lblNumLote.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumLote.setForeground(new java.awt.Color(0, 153, 51));
        lblNumLote.setText("NumeroLote");

        jLabel5.setText("Lugar de producción:");

        jLabel6.setText("Número de Lote:");

        tblPlagasAsociadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Nombre de la Plaga", "Cantidad de plantas infestadas", "Porcentaje de infestación"
            }
        ));
        jScrollPane1.setViewportView(tblPlagasAsociadas);

        btnEditarPlaga.setText("Editar información de plaga");
        btnEditarPlaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPlagaActionPerformed(evt);
            }
        });

        jLabel7.setText("Presiona \"Eliminar plaga(s) de la inspección\" para eliminar la o las plagas seleccionadas de la inspección.");

        jLabel8.setText("Fecha Inspección:");

        lblFechaInspec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaInspec.setForeground(new java.awt.Color(0, 153, 51));
        lblFechaInspec.setText("FechaInspec");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNumLote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(165, 165, 165))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombreLugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lblFechaInspec, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditarPlaga)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarPlaga))
            .addComponent(jScrollPane1)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreLugar)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(lblFechaInspec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumLote)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnEliminarPlaga)
                    .addComponent(btnEditarPlaga))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarPlagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPlagaActionPerformed
        InspeccionPlagaDAO daoIP = new InspeccionPlagaDAO();
        DefaultTableModel model = (DefaultTableModel) tblPlagasAsociadas.getModel();
        
        int [] selected = tblPlagasAsociadas.getSelectedRows();
        
        if (selected.length < 1) {
            JOptionPane.showMessageDialog(this,
                "Debes seleccionar una o más plagas para eliminar.",
                "Sin plaga seleccionada",
                JOptionPane.WARNING_MESSAGE);
        } else {
            int confirmacion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Estás seguro de eliminar las plagas seleccionadas?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE
            );
            if (confirmacion == JOptionPane.YES_OPTION){
                int eliminados = 0;
                java.util.Arrays.sort(selected);
                for (int idx = selected.length - 1; idx >= 0; idx--){
                    int row = selected[idx];
                    try {
                        String idPlagaSelec = tblPlagasAsociadas.getValueAt(row, 0).toString();
                        String nomPlagaSelec = tblPlagasAsociadas.getValueAt(row, 1).toString();
                        boolean ok = daoIP.eliminar(IdInspeccion, idPlagaSelec);
                        
                        if (ok) {
                            model.removeRow(row);
                            eliminados++;
                        } else {
                            JOptionPane.showMessageDialog(
                                    this,
                                    "No se pudo eliminar la plaga con nombre: " + nomPlagaSelec,
                                    "Error",
                                    JOptionPane.ERROR_MESSAGE
                            );
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(
                                this,
                                "Error inesperado al eliminar la plaga en la fila " + row + ": " + e.getMessage(),
                                "Error",
                                JOptionPane.ERROR_MESSAGE
                        );
                    }
                }
                if (eliminados >0){
                    JOptionPane.showMessageDialog(
                            this,
                            eliminados + " plaga(s) eliminada(s) correctamente."
                    );
                } else {
                    JOptionPane.showMessageDialog(
                            this,
                            "No se eliminó ninguna plaga asociada a la inspección."
                    );
                }
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Eliminación cancelada por el usuario."
                );
            }
        }
    }//GEN-LAST:event_btnEliminarPlagaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Dashboard.ShowJPanel(new GestionInspeccionesFitosanitarias());
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarPlagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPlagaActionPerformed
        int plagaS = tblPlagasAsociadas.getSelectedRow();
        if (plagaS == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una plaga de la tabla para editar.");
            return;
        }

        // Supongamos que la columna 0 tiene el id
        String idPlagaS = tblPlagasAsociadas.getValueAt(plagaS, 0).toString();
        String nomPlagaS = tblPlagasAsociadas.getValueAt(plagaS, 1).toString();
        int cantidadPlagaS = (int) tblPlagasAsociadas.getValueAt(plagaS, 2);
        // Buscar la plaga en la BD
        try {
            UpInspeccionPlagaExtra panelEditar = new UpInspeccionPlagaExtra(true, inspeccionActual, idPlagaS, nomPlagaS, cantidadPlagaS);
            // Mostrar el panel en el Dashboard
            Dashboard.ShowJPanel(panelEditar);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al obtener la plaga: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditarPlagaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditarPlaga;
    private javax.swing.JButton btnEliminarPlaga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFechaInspec;
    private javax.swing.JLabel lblNombreLugar;
    private javax.swing.JLabel lblNumLote;
    private javax.swing.JTable tblPlagasAsociadas;
    // End of variables declaration//GEN-END:variables
}
