/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Clases.vistas;

import Clases.dao.InspeccionPlagaDAO;
import Clases.libreria.Dashboard;
import Clases.modelo.InspeccionFitosanitaria;
import javax.swing.JOptionPane;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

/**
 *
 * @author ricar
 */
public class UpInspeccionPlagaExtra extends javax.swing.JPanel {
    
    private String IdInspeccion;
    private String IdPlaga;
    private int cantidadPlantas;
    private String nomPlaga;
    private int cantidadInfest;
    private boolean valorCondicion; 
    InspeccionFitosanitaria inspeccionActual;
    
    public UpInspeccionPlagaExtra(boolean valorCondicion, InspeccionFitosanitaria inspeccionActual, String idPlaga, String nomPlaga, int cantidadInfestada) {
        initComponents();
        configurarCamposEditables();
        this.inspeccionActual = inspeccionActual;
        IdInspeccion = inspeccionActual.getIdInspeccion();
        IdPlaga = idPlaga;
        this.nomPlaga = nomPlaga;
        lblNombrePlaga.setText(nomPlaga);
        lblNombreLugar.setText(inspeccionActual.getNombreLugarProduccion());
        lblNumLote.setText(inspeccionActual.getNumeroLote());
        lblFechaInspec.setText(inspeccionActual.getFecInspeccion().toString());
        cantidadPlantas = inspeccionActual.getCantidadPlantas();
        txtCantidadPlantas.setText(Integer.toString(cantidadPlantas));
        this.cantidadInfest = cantidadInfestada;
        txtCantidadInfestada.setText(Integer.toString(cantidadInfest));
        txtPorcentajeInfest.setText(Float.toString(((float)cantidadInfest/cantidadPlantas)*100));
        this.valorCondicion = valorCondicion;
        configurarVisibilidadBoton();
    }
    
    private void configurarVisibilidadBoton() {
        if (valorCondicion) {
            btnVolverMenu.setVisible(true);
        } else {
            btnVolverMenu.setVisible(false);
        }
        
        // Forma abreviada:
        // btnCondicional.setVisible(esCondicionX);
    }
    
    private void configurarCamposEditables() {
        txtCantidadPlantas.setEditable(false);
        txtCantidadInfestada.setEditable(true);
        txtPorcentajeInfest.setEditable(false);
        // Añade el FocusListener al campo de cantidad infestada
        txtCantidadInfestada.addFocusListener(new FocusListener() {
        @Override
        public void focusGained(FocusEvent e) {
            // Este método se ejecuta cuando el campo gana el foco (el usuario hace clic en él)
        }

        @Override
        public void focusLost(FocusEvent e) {
            // ESTE MÉTODO SE EJECUTA CUANDO EL CAMPO PIERDE EL FOCO (el usuario sale de él)
            calcularResultado();
        }
    });
    }
    
    private void calcularResultado() {
        String valorStr = txtCantidadInfestada.getText();
        try {
            // Intenta convertir el texto a un número (double)
            cantidadInfest = Integer.parseInt(valorStr);
            float porcentajeInfest = ((float)cantidadInfest / cantidadPlantas) * 100; 
            // Opcional: Formatear el resultado a dos decimales para que se vea mejor
            String porcentajeI = String.format("%.2f", porcentajeInfest);
            // Establece el resultado en el segundo text field
            txtPorcentajeInfest.setText(porcentajeI); 
        } catch (NumberFormatException ex) {
            // Maneja el error si el usuario no introdujo un número válido
            if (!valorStr.isEmpty()) { // Muestra el error solo si el campo no está vacío
                JOptionPane.showMessageDialog(null, "Por favor, introduce un valor numérico válido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
                txtCantidadInfestada.requestFocus(); // Opcional: vuelve a poner el foco en el campo erróneo
            }
            txtPorcentajeInfest.setText(""); // Limpia el campo de resultado si hay error
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardarPlagasInspec = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblNombreLugar = new javax.swing.JLabel();
        lblNumLote = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCantidadPlantas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCantidadInfestada = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblNombrePlaga = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPorcentajeInfest = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnVolverMenu = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        lblFechaInspec = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(770, 430));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 430));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("A continuación, actualiza la siguiente información para la plaga que asociaste al lote y lugar de producción:");

        jLabel2.setText("Cantidad de plantas:");

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardarPlagasInspec.setBackground(new java.awt.Color(51, 153, 0));
        btnGuardarPlagasInspec.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardarPlagasInspec.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarPlagasInspec.setText("Guardar");
        btnGuardarPlagasInspec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPlagasInspecActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setText("Este primer campo representa la cantidad de plantas que se contaron durante");

        lblNombreLugar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreLugar.setForeground(new java.awt.Color(0, 153, 51));
        lblNombreLugar.setText("NombreLugarPr");

        lblNumLote.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumLote.setForeground(new java.awt.Color(0, 153, 51));
        lblNumLote.setText("NumeroLote");

        jLabel5.setText("Lugar de producción:");

        jLabel6.setText("Número de Lote:");

        jLabel7.setText("* Cantidad de plantas infestadas");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel8.setText(" la inspección fitosanitaria.");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel9.setText("Este segundo campo representa la cantidad de plantas que se detectaron estaban");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel10.setText("infestadas por la plaga en cuestión.");

        jLabel11.setText("Plaga asociada:");

        lblNombrePlaga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombrePlaga.setForeground(new java.awt.Color(0, 153, 51));
        lblNombrePlaga.setText("NombrePlaga");

        jLabel12.setText("Porcentaje de infestación");

        txtPorcentajeInfest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorcentajeInfestActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel13.setText("Se calcula como: (cantidad plantas infestadas / cantidad plantas) * 100");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel14.setText("Este tercer campo se calcula y rellena automáticamente.");

        btnVolverMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolverMenu.setForeground(new java.awt.Color(204, 153, 0));
        btnVolverMenu.setText("Volver al menú anterior");
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });

        jLabel15.setText("Fecha inspección:");

        lblFechaInspec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaInspec.setForeground(new java.awt.Color(0, 153, 51));
        lblFechaInspec.setText("FechaInspec");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreLugar)
                            .addComponent(lblNombrePlaga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(lblNumLote, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(lblFechaInspec, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVolverMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(117, 117, 117)
                        .addComponent(btnGuardarPlagasInspec))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPorcentajeInfest, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(txtCantidadPlantas)
                            .addComponent(txtCantidadInfestada)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreLugar)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(lblNumLote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(lblFechaInspec))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(lblNombrePlaga)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCantidadPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCantidadInfestada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPorcentajeInfest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarPlagasInspec)
                    .addComponent(btnCancelar)
                    .addComponent(btnVolverMenu))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarPlagasInspecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPlagasInspecActionPerformed
        if (txtCantidadPlantas.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, ingrese datos en el campo de plantas infestadas.",
                    "Campos incompletos",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (cantidadInfest > cantidadPlantas ){
            JOptionPane.showMessageDialog(this,
                    "La cantidad de plantas infestadas NO puede ser mayor a la cantidad total de plantas.",
                    "Error cantidad de plantas infestadas",
                    JOptionPane.WARNING_MESSAGE);
            return;
        } else if(cantidadInfest <= 0){
            JOptionPane.showMessageDialog(this,
                    "La cantidad de plantas infestadas NO puede ser menor o igual a cero.",
                    "Error cantidad de plantas infestadas",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            InspeccionPlagaDAO plagaDao = new InspeccionPlagaDAO();
            // CONVERTIR STRINGS A TIPOS NUMÉRICOS ANTES de llamar al DAO
            int cantidad = Integer.parseInt(txtCantidadInfestada.getText());
            // Usamos Float.parseFloat porque es lo que usas en calcularResultado
            String porcentajeStr = txtPorcentajeInfest.getText().replaceAll(",", ".");
            float porcentaje = Float.parseFloat(porcentajeStr);
            boolean guardado = plagaDao.insertarInspecPlagaCantidad(IdInspeccion, IdPlaga, cantidad, porcentaje);
            if (guardado) {
                
                if(valorCondicion) {
                    Object[] opciones = {"Editar Otra Plaga", "Menú Principal"};
                // 2. Muestra el cuadro de diálogo con las opciones personalizadas
                    int seleccion = JOptionPane.showOptionDialog(
                        this, // Componente padre
                        "Se guardó satisfactoriamente la información.\n¿Deseas volver al menú principal o editar otra plaga asociada a la inspección?", // Mensaje
                        "Guardado Exitoso", // Título de la ventana
                        JOptionPane.YES_NO_OPTION, // Tipo de opciones (usamos YES_NO_OPTION como base)
                        JOptionPane.QUESTION_MESSAGE, // Tipo de icono (o INFORMATION_MESSAGE, como prefieras)
                        null, // Icono personalizado (null para usar el predeterminado)
                        opciones, // Array de los textos de los botones
                        opciones[0] // Opción predeterminada (Asociar Otra Plaga)
                    );
                    // 3. Maneja la respuesta del usuario
                    // showOptionDialog devuelve el índice del botón presionado (0 para la primera opción, 1 para la segunda)
                    if (seleccion == 0) {
                        // El usuario seleccionó "Asociar Otra Plaga" (índice 0)
                        Dashboard.ShowJPanel(new UpInspeccionPlagaUpdate(inspeccionActual));
                    } else if (seleccion == 1) {
                        // El usuario seleccionó "Menú Principal" (índice 1)
                        Dashboard.ShowJPanel(new GestionInspeccionesFitosanitarias());
                    } else {
                        // El usuario cerró el diálogo sin seleccionar nada (opcional)
                        System.out.println("Diálogo cerrado sin selección.");
                        Dashboard.ShowJPanel(new GestionInspeccionesFitosanitarias());
                    }
                } else if(!valorCondicion){
                    Object[] opciones = {"Asociar Otra Plaga", "Menú Principal"};
                // 2. Muestra el cuadro de diálogo con las opciones personalizadas
                    int seleccion = JOptionPane.showOptionDialog(
                        this, // Componente padre
                        "Se guardó satisfactoriamente la información.\n¿Deseas volver al menú principal o asociar una nueva plaga en la inspección?", // Mensaje
                        "Guardado Exitoso", // Título de la ventana
                        JOptionPane.YES_NO_OPTION, // Tipo de opciones (usamos YES_NO_OPTION como base)
                        JOptionPane.QUESTION_MESSAGE, // Tipo de icono (o INFORMATION_MESSAGE, como prefieras)
                        null, // Icono personalizado (null para usar el predeterminado)
                        opciones, // Array de los textos de los botones
                        opciones[0] // Opción predeterminada (Asociar Otra Plaga)
                    );
                    // 3. Maneja la respuesta del usuario
                    // showOptionDialog devuelve el índice del botón presionado (0 para la primera opción, 1 para la segunda)
                    if (seleccion == 0) {
                        // El usuario seleccionó "Asociar Otra Plaga" (índice 0)
                        Dashboard.ShowJPanel(new UpInspeccionPlaga(inspeccionActual));
                    } else if (seleccion == 1) {
                        // El usuario seleccionó "Menú Principal" (índice 1)
                        Dashboard.ShowJPanel(new GestionInspeccionesFitosanitarias());
                    } else {
                        // El usuario cerró el diálogo sin seleccionar nada (opcional)
                        System.out.println("Diálogo cerrado sin selección.");
                        Dashboard.ShowJPanel(new GestionInspeccionesFitosanitarias());
                    }
                }
                
                
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se pudo guardar la información de la cantidad de plantas infestadas.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al guardar: " + e.getMessage());
            e.printStackTrace();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarPlagasInspecActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Dashboard.ShowJPanel(new GestionInspeccionesFitosanitarias());
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtPorcentajeInfestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorcentajeInfestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorcentajeInfestActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        Dashboard.ShowJPanel(new UpInspeccionPlagaUpdate(inspeccionActual));
    }//GEN-LAST:event_btnVolverMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardarPlagasInspec;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblFechaInspec;
    private javax.swing.JLabel lblNombreLugar;
    private javax.swing.JLabel lblNombrePlaga;
    private javax.swing.JLabel lblNumLote;
    private javax.swing.JTextField txtCantidadInfestada;
    private javax.swing.JTextField txtCantidadPlantas;
    private javax.swing.JTextField txtPorcentajeInfest;
    // End of variables declaration//GEN-END:variables
}
