/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Clases.vistas;

import Clases.dao.EspecieVegetalDAO;
import Clases.dao.LugarEspecieDAO;
import Clases.dao.PredioDAO;
import Clases.libreria.Dashboard;
import Clases.modelo.LugarProduccion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricar
 */
public class UpLugarProdRegistrarProyeccion extends javax.swing.JPanel {

    private String idLugarProduccion;
    private LugarProduccion lugarproduccionActual;
    private String nombreLP;

    private String nombreRol;

    public UpLugarProdRegistrarProyeccion(LugarProduccion lugarProduccion) {
        initComponents();
        lugarproduccionActual = lugarProduccion;
        idLugarProduccion = lugarproduccionActual.getIdLugarProduccion();
        nombreLP = lugarproduccionActual.getNomLugarProduccion();
        lblNombreLugarProd.setText(nombreLP);
        lblRegistroICA.setText(lugarproduccionActual.getNroRegistroICA());
        LoadEspecieVNoLP();
    }

    private void LoadEspecieVNoLP() {
        try {
            EspecieVegetalDAO dao = new EspecieVegetalDAO();
            DefaultTableModel model = (DefaultTableModel) tblEspeciesNoLP.getModel();
            model.setRowCount(0); // limpia la tabla

            // Llamamos al nuevo método DAO que devuelve la lista de objetos
            dao.listarNoAsociadasLugarProduccion(idLugarProduccion).forEach((especie) -> {
                model.addRow(new Object[]{
                    especie.getIdEspecie(),
                    especie.getNomEspecie(),
                    especie.getNombreComun(),
                    especie.getCicloCultivo()
                });
            });

            // 🔹 Ocultar la primera columna (id_usuario)
            tblEspeciesNoLP.getColumnModel().getColumn(0).setMinWidth(0);
            tblEspeciesNoLP.getColumnModel().getColumn(0).setMaxWidth(0);
            tblEspeciesNoLP.getColumnModel().getColumn(0).setWidth(0);

        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla de especies vegetales disponibles: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEspeciesNoLP = new javax.swing.JTable();
        btnContinuarProyecc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNombreLugarProd = new javax.swing.JLabel();
        lblRegistroICA = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(770, 440));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 440));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Selecciona la especie vegetal que deseas añadir a la proyección de producción del lugar:");

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("Una vez seleccionada la especie vegetal, presiona \"Continuar\" para ingresar los datos de área destinada al cultivo y la capacidad de");

        jLabel4.setText("producción máxima. O si deseas volver al menú principal, presiona \"Cancelar\" para abortar la operación.");

        tblEspeciesNoLP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id_especie", "Nombre científico", "Nombre común", "Ciclo de Cultivo"
            }
        ));
        jScrollPane1.setViewportView(tblEspeciesNoLP);

        btnContinuarProyecc.setBackground(new java.awt.Color(51, 153, 0));
        btnContinuarProyecc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnContinuarProyecc.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuarProyecc.setText("Continuar");
        btnContinuarProyecc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarProyeccActionPerformed(evt);
            }
        });

        jLabel2.setText("Se presentan las especies vegetales disponibles (sin asociar al lugar).  Debes seleccionar una a la vez para continuar:");

        jLabel6.setText("Registro ICA:");

        jLabel5.setText("Nombre Lugar:");

        lblNombreLugarProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreLugarProd.setForeground(new java.awt.Color(0, 153, 51));
        lblNombreLugarProd.setText("NombreLugarPr");

        lblRegistroICA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRegistroICA.setForeground(new java.awt.Color(0, 153, 51));
        lblRegistroICA.setText("RegistroICA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnContinuarProyecc, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblRegistroICA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombreLugarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblNombreLugarProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblRegistroICA))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinuarProyecc)
                    .addComponent(btnCancelar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarProyeccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarProyeccActionPerformed
        int especieS = tblEspeciesNoLP.getSelectedRow();
        if (especieS == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una especie de la tabla para continuar.");
            return;
        }
        int[] especiesS = tblEspeciesNoLP.getSelectedRows();
        if (especiesS.length > 1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione SOLO UNA especie de la tabla para continuar.");
            return;
        }
        // Supongamos que la columna 0 tiene el id
        String idEspecieS = tblEspeciesNoLP.getValueAt(especieS, 0).toString();
        EspecieVegetalDAO daoEspecie = new EspecieVegetalDAO();
        Clases.modelo.EspecieVegetal especieV = daoEspecie.buscarPorId(idEspecieS);

        // Buscar la especie en la BD
        try {
            LugarEspecieDAO lugarEspec = new LugarEspecieDAO();
            lugarEspec.insertar(idLugarProduccion, idEspecieS);
            UpLugarProdRegProyecContinuar panelEditar = new UpLugarProdRegProyecContinuar(false, lugarproduccionActual, especieV, 0.0f, 0.0f);
            JOptionPane.showMessageDialog(this,
                    "Especie asociada correctamente a la proyección de producción del lugar");
            // Mostrar el panel en el Dashboard
            Dashboard.ShowJPanel(panelEditar);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al obtener la plaga: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnContinuarProyeccActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Dashboard.ShowJPanel(new GestionLugaresProduccion());
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContinuarProyecc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreLugarProd;
    private javax.swing.JLabel lblRegistroICA;
    private javax.swing.JTable tblEspeciesNoLP;
    // End of variables declaration//GEN-END:variables
}
