/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Clases.vistas;

import Clases.modelo.LugarProduccion;
import Clases.dao.LugarProduccionDAO;
import Clases.dao.UsuarioDAO;
import Clases.libreria.Dashboard;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author ricar
 */
public class UpLugarProduccion extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public UpLugarProduccion() {
        initComponents();
        cargarUsuarios();
    }

    private void limpiarCampos() {
        txtNombre.setText("");
        txtRegistroICA.setText("");
        jBoxUsuarioProductor.setSelectedIndex(0);
    }

    private void cargarUsuarios() {
        try {
            UsuarioDAO dao = new UsuarioDAO();
            jBoxUsuarioProductor.removeAllItems();
            jBoxUsuarioProductor.addItem("Seleccione el productor");

            dao.listarTodos().forEach(usu -> jBoxUsuarioProductor.addItem(usu.getNombreCompleto()));

            // ?Habilitar autocompletado
            AutoCompleteDecorator.decorate(jBoxUsuarioProductor);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtRegistroICA = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBoxUsuarioProductor = new javax.swing.JComboBox<>();
        btnSelectPredios = new javax.swing.JButton();
        btnSelectEspecVegetales = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 430));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 430));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nuevo Lugar de Producción:");

        jLabel2.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtRegistroICA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroICAActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(51, 153, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar Lugar de Producción");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel4.setText("Numero Registro ICA");

        jLabel3.setText("Productor");

        jBoxUsuarioProductor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jBoxUsuarioProductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxUsuarioProductorActionPerformed(evt);
            }
        });

        btnSelectPredios.setBackground(new java.awt.Color(153, 153, 153));
        btnSelectPredios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSelectPredios.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectPredios.setText("Selecciona los Predios");
        btnSelectPredios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectPrediosActionPerformed(evt);
            }
        });

        btnSelectEspecVegetales.setBackground(new java.awt.Color(153, 153, 153));
        btnSelectEspecVegetales.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSelectEspecVegetales.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectEspecVegetales.setText("Selecciona las Especies Vegetales");
        btnSelectEspecVegetales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectEspecVegetalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre)
                    .addComponent(jBoxUsuarioProductor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRegistroICA)
                    .addComponent(btnSelectPredios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 398, Short.MAX_VALUE)
                        .addComponent(btnGuardar))
                    .addComponent(btnSelectEspecVegetales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRegistroICA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBoxUsuarioProductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSelectPredios)
                .addGap(18, 18, 18)
                .addComponent(btnSelectEspecVegetales)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtNombre.getText().trim().isEmpty()
                || txtRegistroICA.getText().trim().isEmpty()
                || jBoxUsuarioProductor.getSelectedIndex() <= 0) {

            JOptionPane.showMessageDialog(this,
                    "Por favor, complete todos los campos antes de guardar.",
                    "Campos incompletos",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 🔹 Obtener el nombre seleccionado
            String nombreUsuario = (String) jBoxUsuarioProductor.getSelectedItem();

            // 🔹 Buscar ID del departamento
            Clases.dao.UsuarioDAO usuDAO = new Clases.dao.UsuarioDAO();
            String idUsu = usuDAO.obtenerIdUsuarioPorNombre(nombreUsuario);

            if (idUsu == null) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró el ID del usuario seleccionado.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 🔹 Crear lugar produccion con el ID correcto
            LugarProduccion lugarproduccion = new LugarProduccion();
            lugarproduccion.setNomLugarProduccion(txtNombre.getText());
            lugarproduccion.setNroRegistroICA(txtRegistroICA.getText());
            lugarproduccion.setIdUsuarioProductor(idUsu); // ✅ Guardamos el ID real

            // 🔹 Insertar en la BD
            Clases.dao.LugarProduccionDAO lugarproduccionDAO = new Clases.dao.LugarProduccionDAO();
            boolean guardado = lugarproduccionDAO.insertar(lugarproduccion);

            if (guardado) {
                JOptionPane.showMessageDialog(this, "Lugar de produccion guardado correctamente");
                limpiarCampos();
                Dashboard.ShowJPanel(new GestionLugaresProduccion());
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo guardar el Lugar de produccion");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarCampos();
        Dashboard.ShowJPanel(new GestionLugaresProduccion());
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtRegistroICAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroICAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroICAActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jBoxUsuarioProductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxUsuarioProductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBoxUsuarioProductorActionPerformed

    private void btnSelectPrediosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectPrediosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectPrediosActionPerformed

    private void btnSelectEspecVegetalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectEspecVegetalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectEspecVegetalesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSelectEspecVegetales;
    private javax.swing.JButton btnSelectPredios;
    private javax.swing.JComboBox<String> jBoxUsuarioProductor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRegistroICA;
    // End of variables declaration//GEN-END:variables
}
