/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Clases.vistas;

import Clases.dao.PredioDAO;
import Clases.libreria.Dashboard;
import Clases.modelo.LugarProduccion;
import Clases.vistas.GestionLugaresProduccion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricar
 */
public class UpLugarProdPredios extends javax.swing.JPanel {

    private String idLugarProduccion;
    private LugarProduccion lugarproduccionActual;
    private String nombreLP;


    public UpLugarProdPredios(LugarProduccion lugarProduccion) {
        initComponents();
        LoadPrediosSinLP();
        lugarproduccionActual = lugarProduccion;
        idLugarProduccion = lugarproduccionActual.getIdLugarProduccion();
        nombreLP = lugarproduccionActual.getNomLugarProduccion();
        lblNombreLugarProd.setText(nombreLP);
        lblRegistroICA.setText(lugarproduccionActual.getNroRegistroICA());
    }

    private void LoadPrediosSinLP() {
        try {
            PredioDAO dao = new PredioDAO();
            DefaultTableModel model = (DefaultTableModel) tblPrediosLP.getModel();
            model.setRowCount(0); // limpia la tabla

            // Llamamos al nuevo método DAO que devuelve la lista de objetos
            dao.listarNoAsociadosLugarProduccion().forEach((predio) -> {
                model.addRow(new Object[]{
                    predio.getIdPredio(),
                    predio.getNumPredial(),
                    predio.getNroRegistroICA(),
                    predio.getNomPredio()
                });
            });

            // 🔹 Ocultar la primera columna (id_usuario)
            tblPrediosLP.getColumnModel().getColumn(0).setMinWidth(0);
            tblPrediosLP.getColumnModel().getColumn(0).setMaxWidth(0);
            tblPrediosLP.getColumnModel().getColumn(0).setWidth(0);

        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla de predios: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNombreLugarProd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrediosLP = new javax.swing.JTable();
        btnAsociarPredios = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblRegistroICA = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(770, 430));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 430));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Selecciona el(los) predio(s) que conformará(n) el lugar de producción:");

        jLabel2.setText("Se presentan los predios disponibles (sin asociar a ningún lugar).  Puedes seleccionar varios manteniendo presionada la tecla \"Ctrl\":");

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("Una vez seleccionado el o los predios que conformarán el lugar de producción, presiona \"Asociar Predios al Lugar\" para guardar ");

        jLabel4.setText("los cambios y volver al menú principal, o \"Cancelar\" para abortar la operación.");

        lblNombreLugarProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreLugarProd.setForeground(new java.awt.Color(0, 153, 51));
        lblNombreLugarProd.setText("NombreLugarPr");

        tblPrediosLP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id_predio", "Número Predial", "Registro ICA", "Nombre del Predio"
            }
        ));
        jScrollPane1.setViewportView(tblPrediosLP);

        btnAsociarPredios.setBackground(new java.awt.Color(51, 153, 0));
        btnAsociarPredios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAsociarPredios.setForeground(new java.awt.Color(255, 255, 255));
        btnAsociarPredios.setText("Asociar Predios al Lugar");
        btnAsociarPredios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsociarPrediosActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre Lugar:");

        jLabel6.setText("Registro ICA:");

        lblRegistroICA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRegistroICA.setForeground(new java.awt.Color(0, 153, 51));
        lblRegistroICA.setText("RegistroICA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAsociarPredios, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblRegistroICA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombreLugarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblNombreLugarProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblRegistroICA))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAsociarPredios))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsociarPrediosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsociarPrediosActionPerformed
        PredioDAO daoPredioLP = new PredioDAO();
        DefaultTableModel model = (DefaultTableModel) tblPrediosLP.getModel();

        int[] selectedRows = tblPrediosLP.getSelectedRows();

        if (selectedRows.length < 1) {
            JOptionPane.showMessageDialog(this,
                    "Debes seleccionar uno o más predios para asociarlos al lugar.",
                    "Sin predio seleccionado",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            int asociados = 0;
            // Ordenamos los índices de mayor a menor para eliminar correctamente del modelo
            java.util.Arrays.sort(selectedRows);

            // Iteramos de atrás hacia adelante para que la eliminación de filas no afecte los índices.
            for (int idx = selectedRows.length - 1; idx >= 0; idx--) {
                int row = selectedRows[idx];

                try {
                    // Columna 0 contiene el ID_PREDIO
                    String idPredio = tblPrediosLP.getValueAt(row, 0).toString();

                    // Columna 1 contiene el NUM_PREDIAL (solo para mensaje de error)
                    String numPredial = tblPrediosLP.getValueAt(row, 1).toString();

                    // ⭐ LLAMAR AL NUEVO MÉTODO PARA ASOCIAR EL PREDIO
                    boolean ok = daoPredioLP.asociarLugarProduccion(idPredio, this.idLugarProduccion);

                    if (ok) {
                        model.removeRow(row); // Quitar el predio de la tabla de "no asociados"
                        asociados++;
                    } else {
                        // El error se muestra dentro del método DAO, pero puedes poner un mensaje extra aquí
                        JOptionPane.showMessageDialog(
                                this,
                                "No se pudo asociar el predio " + numPredial + " al lugar de producción.",
                                "Error de Asociación",
                                JOptionPane.ERROR_MESSAGE
                        );
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(
                            this,
                            "Error inesperado al asociar predio en la fila " + row + ": " + e.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }

            if (asociados > 0) {
                JOptionPane.showMessageDialog(
                        this,
                        asociados + " predio(s) asociado(s) correctamente"
                );

                Object[] opciones = {"Asociar más predios", "Menú Principal"};
                // 2. Muestra el cuadro de diálogo con las opciones personalizadas
                int seleccion = JOptionPane.showOptionDialog(
                        this, // Componente padre
                        "¿Deseas volver al menú principal o asociar otro predio al lugar de producción?", // Mensaje
                        "Guardado Exitoso", // Título de la ventana
                        JOptionPane.YES_NO_OPTION, // Tipo de opciones (usamos YES_NO_OPTION como base)
                        JOptionPane.QUESTION_MESSAGE, // Tipo de icono (o INFORMATION_MESSAGE, como prefieras)
                        null, // Icono personalizado (null para usar el predeterminado)
                        opciones, // Array de los textos de los botones
                        opciones[0] // Opción predeterminada (Asociar Otra Plaga)
                );
                // 3. Maneja la respuesta del usuario
                // showOptionDialog devuelve el índice del botón presionado (0 para la primera opción, 1 para la segunda)
                if (seleccion == 1) {
                    Dashboard.ShowJPanel(new GestionLugaresProduccion());
                }

            } else {
                // Si hay un error, el mensaje de error se mostrará en el bucle
                JOptionPane.showMessageDialog(
                        this,
                        "No se asoció ningún predio."
                );
            }
        }


    }//GEN-LAST:event_btnAsociarPrediosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Dashboard.ShowJPanel(new GestionLugaresProduccion());
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsociarPredios;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreLugarProd;
    private javax.swing.JLabel lblRegistroICA;
    private javax.swing.JTable tblPrediosLP;
    // End of variables declaration//GEN-END:variables
}
