/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Clases.vistas;

import Clases.dao.LugarEspecieDAO;
import Clases.libreria.Dashboard;
import Clases.modelo.LugarProduccion;
import Clases.modelo.EspecieVegetal;
import javax.swing.JOptionPane;

/**
 *
 * @author ricar
 */
public class UpLugarProdRegProyecContinuar extends javax.swing.JPanel {
    
    private boolean valorCondicion; 
    private LugarProduccion lugarPActual;
    private String IdLugarPActual;
    private String IdEspecieActual;
    private String nomComunEActual;
    private String cicloCultivoActual;
    private float areaDestinadaActual;
    private float capacidadMaximaActual;
    
    
    private String nombreRol;
    
    public UpLugarProdRegProyecContinuar(boolean valorCondicion, LugarProduccion lugarActual, EspecieVegetal especieVegetal, float areaDestinada, float capacidadMaxima) {
        this.nombreRol = nombreRol;
        initComponents();
        lugarPActual = lugarActual;
        IdLugarPActual = lugarPActual.getIdLugarProduccion();
        IdEspecieActual = especieVegetal.getIdEspecie();
        nomComunEActual = especieVegetal.getNombreComun();
        areaDestinadaActual = areaDestinada;
        capacidadMaximaActual = capacidadMaxima;
        cicloCultivoActual = especieVegetal.getCicloCultivo();
        
        lblCicloCult.setText(cicloCultivoActual);
        lblNombreEspecie.setText(nomComunEActual);
        lblNombreLugar.setText(lugarPActual.getNomLugarProduccion());
        lblRegistroICA.setText(lugarPActual.getNroRegistroICA());
        
        txtAreaDestinada.setText(Float.toString(areaDestinadaActual));
        txtCapacidadMax.setText(Float.toString(capacidadMaximaActual));
        
        this.valorCondicion = valorCondicion;
        configurarVisibilidadBoton();
        definirPeriodoCapacidad();
    }
    
    private void configurarVisibilidadBoton() {
        if (valorCondicion) {
            btnVolverMenu.setVisible(true);
        } else {
            btnVolverMenu.setVisible(false);
        }
    }
    
    private void definirPeriodoCapacidad() {
        String ciclo = cicloCultivoActual.split(" \\( ")[0].trim();
        if (ciclo.equals("Largo")){
            lblPeriodo.setText("kg/año");
        } else{
            lblPeriodo.setText("kg/mes");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardarEspecieLugar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblNombreLugar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAreaDestinada = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCapacidadMax = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblNombreEspecie = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnVolverMenu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblCicloCult = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblRegistroICA = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(770, 430));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 430));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("A continuación, actualiza la siguiente información para la especie que asociaste a la proyección del lugar:");

        jLabel2.setText("Área destinada al cultivo [ha]");

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardarEspecieLugar.setBackground(new java.awt.Color(51, 153, 0));
        btnGuardarEspecieLugar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardarEspecieLugar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarEspecieLugar.setText("Guardar");
        btnGuardarEspecieLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEspecieLugarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setText("Este primer campo representa la proyección del área destinada al cultivo de");

        lblNombreLugar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreLugar.setForeground(new java.awt.Color(0, 153, 51));
        lblNombreLugar.setText("NombreLugarPr");

        jLabel5.setText("Lugar de producción:");

        jLabel7.setText("Capacidad de producción [kg]");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel8.setText("dicha especie vegetal. La unidad de medida estará expresada en \"hectáreas\".");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel9.setText("Este segundo campo representa la proyección de la capacidad de producción");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel10.setText("máxima para dicha especie vegetal. La unidad de medida estará");

        jLabel11.setText("Especie asociada:");

        lblNombreEspecie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreEspecie.setForeground(new java.awt.Color(0, 153, 51));
        lblNombreEspecie.setText("NombreEspecie");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel14.setText("expresada en kilogramos. Será anual  para cultivos de ciclo largo, y mensual");

        btnVolverMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolverMenu.setForeground(new java.awt.Color(204, 153, 0));
        btnVolverMenu.setText("Volver al menú anterior");
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel4.setText("en los demás casos. ");

        lblPeriodo.setBackground(new java.awt.Color(218, 215, 215));
        lblPeriodo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPeriodo.setText("periodo");
        lblPeriodo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblPeriodo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblPeriodo.setOpaque(true);

        jLabel12.setText("Ciclo de cultivo de la especie:");

        lblCicloCult.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCicloCult.setForeground(new java.awt.Color(0, 153, 51));
        lblCicloCult.setText("CicloCultivo");

        jLabel6.setText("Nota: utiliza el símbolo punto (.) como separador decimal. NO utilices la coma (,), de lo contrario no podrás guardar la información. ");

        jLabel13.setText("Registro ICA:");

        lblRegistroICA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRegistroICA.setForeground(new java.awt.Color(0, 153, 51));
        lblRegistroICA.setText("RegistroICA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVolverMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(117, 117, 117)
                        .addComponent(btnGuardarEspecieLugar))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                    .addComponent(txtAreaDestinada)
                                    .addComponent(txtCapacidadMax)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreLugar)
                                    .addComponent(lblNombreEspecie))))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(lblCicloCult))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblRegistroICA, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(lblRegistroICA))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNombreLugar)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblNombreEspecie)
                    .addComponent(jLabel12)
                    .addComponent(lblCicloCult))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAreaDestinada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCapacidadMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPeriodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarEspecieLugar)
                    .addComponent(btnCancelar)
                    .addComponent(btnVolverMenu))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarEspecieLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEspecieLugarActionPerformed
        if (txtAreaDestinada.getText().trim().isEmpty()
            || txtCapacidadMax.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, completa todos los campos para guardar.",
                    "Campos incompletos",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        areaDestinadaActual = Float.parseFloat(txtAreaDestinada.getText());
        capacidadMaximaActual = Float.parseFloat(txtCapacidadMax.getText());
        if (areaDestinadaActual <= 0
            || capacidadMaximaActual <= 0) {
            JOptionPane.showMessageDialog(this,
                    "El área destinada al cultivo o la capacidad máxima de producción no puede ser menor o igual a 0.",
                    "Error datos de área o capacidad",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        LugarEspecieDAO lugarEspDao = new LugarEspecieDAO();
        String area = txtAreaDestinada.getText().replaceAll(",", ".");
        float areaF = Float.parseFloat(area);
        String capacidad = txtCapacidadMax.getText().replaceAll(",", ".");
        float capacidadF = Float.parseFloat(capacidad);
        try {
            boolean guardado = lugarEspDao.actualizarDetalles(IdLugarPActual, IdEspecieActual, areaF, capacidadF);
            if (guardado) {
                if(!valorCondicion) {
                    Object[] opciones = {"Registrar Proyección", "Menú Principal"};
                // 2. Muestra el cuadro de diálogo con las opciones personalizadas
                    int seleccion = JOptionPane.showOptionDialog(
                        this, // Componente padre
                        "Se guardó satisfactoriamente la información.\n¿Deseas volver al menú principal o registrar otra proyección de producción al lugar?", // Mensaje
                        "Guardado Exitoso", // Título de la ventana
                        JOptionPane.YES_NO_OPTION, // Tipo de opciones (usamos YES_NO_OPTION como base)
                        JOptionPane.QUESTION_MESSAGE, // Tipo de icono (o INFORMATION_MESSAGE, como prefieras)
                        null, // Icono personalizado (null para usar el predeterminado)
                        opciones, // Array de los textos de los botones
                        opciones[0] // Opción predeterminada (Asociar Otra Plaga)
                    );
                    // 3. Maneja la respuesta del usuario
                    // showOptionDialog devuelve el índice del botón presionado (0 para la primera opción, 1 para la segunda)
                    if (seleccion == 0) {
                        // El usuario seleccionó "Asociar Otra Plaga" (índice 0)
                        Dashboard.ShowJPanel(new UpLugarProdRegistrarProyeccion(lugarPActual));
                    } else if (seleccion == 1) {
                        // El usuario seleccionó "Menú Principal" (índice 1)
                        Dashboard.ShowJPanel(new GestionLugaresProduccion());
                    } else {
                        // El usuario cerró el diálogo sin seleccionar nada (opcional)
                        System.out.println("Diálogo cerrado sin selección.");
                        Dashboard.ShowJPanel(new GestionInspeccionesFitosanitarias());
                    }
                } else if(valorCondicion){
                    Object[] opciones = {"Editar Proyección", "Menú Principal"};
                // 2. Muestra el cuadro de diálogo con las opciones personalizadas
                    int seleccion = JOptionPane.showOptionDialog(
                        this, // Componente padre
                        "Se guardó satisfactoriamente la información.\n¿Deseas volver al menú principal o modificar otra proyección de producción del lugar?", // Mensaje
                        "Guardado Exitoso", // Título de la ventana
                        JOptionPane.YES_NO_OPTION, // Tipo de opciones (usamos YES_NO_OPTION como base)
                        JOptionPane.QUESTION_MESSAGE, // Tipo de icono (o INFORMATION_MESSAGE, como prefieras)
                        null, // Icono personalizado (null para usar el predeterminado)
                        opciones, // Array de los textos de los botones
                        opciones[0] // Opción predeterminada (Asociar Otra Plaga)
                    );
                    // 3. Maneja la respuesta del usuario
                    // showOptionDialog devuelve el índice del botón presionado (0 para la primera opción, 1 para la segunda)
                    if (seleccion == 0) {
                        // El usuario seleccionó "Asociar Otra Plaga" (índice 0)
                        Dashboard.ShowJPanel(new UpLugarProdModificarProyeccion(lugarPActual));
                    } else if (seleccion == 1) {
                        // El usuario seleccionó "Menú Principal" (índice 1)
                        Dashboard.ShowJPanel(new GestionLugaresProduccion());
                    } else {
                        // El usuario cerró el diálogo sin seleccionar nada (opcional)
                        System.out.println("Diálogo cerrado sin selección.");
                        Dashboard.ShowJPanel(new GestionInspeccionesFitosanitarias(nombreRol));
                    }
                }
                
                
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se pudo guardar la información de la cantidad de plantas infestadas.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al guardar: " + e.getMessage());
            e.printStackTrace();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarEspecieLugarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Dashboard.ShowJPanel(new GestionLugaresProduccion());
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        Dashboard.ShowJPanel(new UpLugarProdModificarProyeccion(lugarPActual));
    }//GEN-LAST:event_btnVolverMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardarEspecieLugar;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCicloCult;
    private javax.swing.JLabel lblNombreEspecie;
    private javax.swing.JLabel lblNombreLugar;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblRegistroICA;
    private javax.swing.JTextField txtAreaDestinada;
    private javax.swing.JTextField txtCapacidadMax;
    // End of variables declaration//GEN-END:variables
}
