/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package Clases.vistas;
import Clases.dao.EspecieVegetalDAO;
import Clases.dao.LugarEspecieDAO;
import Clases.dao.PredioDAO;
import Clases.libreria.Dashboard;
import Clases.modelo.LugarProduccion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricar
 */
public class UpLugarProdModificarProyeccion extends javax.swing.JPanel {
    
    private String idLugarProduccion;
    private LugarProduccion lugarproduccionActual;
    private String nombreLP;
    
    public UpLugarProdModificarProyeccion(LugarProduccion lugarProduccion) {
        initComponents();
        lugarproduccionActual = lugarProduccion;
        idLugarProduccion = lugarproduccionActual.getIdLugarProduccion();
        nombreLP = lugarproduccionActual.getNomLugarProduccion();
        lblNombreLugarProd.setText(nombreLP);
        lblRegistroICA.setText(lugarproduccionActual.getNroRegistroICA());
        LoadEspecieVLP();
    }
    
    private void LoadEspecieVLP() {
        try {
            LugarEspecieDAO dao = new LugarEspecieDAO();
            DefaultTableModel model = (DefaultTableModel) tblEspeciesLP.getModel();
            model.setRowCount(0); // limpia la tabla

            // Llamamos al nuevo método DAO que devuelve la lista de objetos
            dao.listarEspeciesAsociadasConDetalles(idLugarProduccion).forEach((especie) -> {
                model.addRow(new Object[]{
                    especie.getIdEspecie(),
                    especie.getNomComun(),
                    especie.getAreaDestCultivo(),
                    especie.getCapacidadProduccionMax()
                });
            });
            
            // 🔹 Ocultar la primera columna (id_usuario)
            tblEspeciesLP.getColumnModel().getColumn(0).setMinWidth(0);
            tblEspeciesLP.getColumnModel().getColumn(0).setMaxWidth(0);
            tblEspeciesLP.getColumnModel().getColumn(0).setWidth(0);
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Error al cargar la tabla de especies vegetales disponibles: " + e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNombreLugarProd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEspeciesLP = new javax.swing.JTable();
        btnEditarProyeccion = new javax.swing.JButton();
        btnEliminarProyeccion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblRegistroICA = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(770, 430));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 430));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Selecciona la especie vegetal que desees modificar o eliminar de la proyección de producción del lugar:");

        jLabel2.setText("Se presentan las especies vegetales que están asociadas al lugar.  Para seleccionar varios registros mantenga presionada la tecla \"Ctrl\":");

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("Una vez seleccionada la especie vegetal, presiona \"Continuar\" para ingresar los datos de área destinada al cultivo y la capacidad de");

        jLabel4.setText("producción máxima. O si deseas volver al menú principal, presiona \"Cancelar\" para abortar la operación.");

        lblNombreLugarProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreLugarProd.setForeground(new java.awt.Color(0, 153, 51));
        lblNombreLugarProd.setText("NombreLugarPr");

        tblEspeciesLP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id_especie", "Especie Vegetal", "Área de cultivo [ha]", "Capacidad producción máx [kg]"
            }
        ));
        jScrollPane1.setViewportView(tblEspeciesLP);

        btnEditarProyeccion.setText("Editar información de proyección");
        btnEditarProyeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProyeccionActionPerformed(evt);
            }
        });

        btnEliminarProyeccion.setText("Eliminar proyección de la inspección");
        btnEliminarProyeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProyeccionActionPerformed(evt);
            }
        });

        jLabel6.setText("Registro ICA:");

        lblRegistroICA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRegistroICA.setForeground(new java.awt.Color(0, 153, 51));
        lblRegistroICA.setText("RegistroICA");

        jLabel7.setText("Nombre Lugar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarProyeccion)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarProyeccion))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreLugarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRegistroICA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreLugarProd)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblRegistroICA))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnEliminarProyeccion)
                    .addComponent(btnEditarProyeccion))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Dashboard.ShowJPanel(new GestionLugaresProduccion());
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarProyeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProyeccionActionPerformed
        int especieS = tblEspeciesLP.getSelectedRow();
        if (especieS == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una plaga de la tabla para editar.");
            return;
        }
        int [] especiesS = tblEspeciesLP.getSelectedRows();
        if (especiesS.length>1){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione SOLO UNA especie de la tabla para continuar.");
            return;
        }
        // Supongamos que la columna 0 tiene el id
        String idEspecieS = tblEspeciesLP.getValueAt(especieS, 0).toString();
        EspecieVegetalDAO daoEspecie = new EspecieVegetalDAO();
        Clases.modelo.EspecieVegetal especieV = daoEspecie.buscarPorId(idEspecieS);
        float areaCultivoS = (float) tblEspeciesLP.getValueAt(especieS, 2);
        float capacidadMaxS = (float) tblEspeciesLP.getValueAt(especieS, 3);
        // Buscar la plaga en la BD
        try {
            UpLugarProdRegProyecContinuar panelEditar = new UpLugarProdRegProyecContinuar(true, lugarproduccionActual, especieV, areaCultivoS, capacidadMaxS);
            // Mostrar el panel en el Dashboard
            Dashboard.ShowJPanel(panelEditar);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al obtener la plaga: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditarProyeccionActionPerformed

    private void btnEliminarProyeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProyeccionActionPerformed
        LugarEspecieDAO daoLP = new LugarEspecieDAO();
        DefaultTableModel model = (DefaultTableModel) tblEspeciesLP.getModel();

        int [] selected = tblEspeciesLP.getSelectedRows();

        if (selected.length < 1) {
            JOptionPane.showMessageDialog(this,
                "Debes seleccionar una o más especies (proyecciones) para eliminar.",
                "Sin especie seleccionada",
                JOptionPane.WARNING_MESSAGE);
        } else {
            int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de eliminar la(s) proyección(es) seleccionada(s)?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );
            if (confirmacion == JOptionPane.YES_OPTION){
                int eliminados = 0;
                java.util.Arrays.sort(selected);
                for (int idx = selected.length - 1; idx >= 0; idx--){
                    int row = selected[idx];
                    try {
                        String idEspecieS = tblEspeciesLP.getValueAt(row, 0).toString();
                        String nomEspecieSelec = tblEspeciesLP.getValueAt(row, 1).toString();
                        boolean ok = daoLP.eliminar(idLugarProduccion, idEspecieS);

                        if (ok) {
                            model.removeRow(row);
                            eliminados++;
                        } else {
                            JOptionPane.showMessageDialog(
                                this,
                                "No se pudo eliminar la especie (proyección) con nombre: " + nomEspecieSelec,
                                "Error",
                                JOptionPane.ERROR_MESSAGE
                            );
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(
                            this,
                            "Error inesperado al eliminar la especie en la fila " + row + ": " + e.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                        );
                    }
                }
                if (eliminados >0){
                    JOptionPane.showMessageDialog(
                        this,
                        eliminados + " especie(s) eliminada(s) correctamente."
                    );
                } else {
                    JOptionPane.showMessageDialog(
                        this,
                        "No se eliminó ninguna especie asociada a la inspección."
                    );
                }
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Eliminación cancelada por el usuario."
                );
            }
        }
    }//GEN-LAST:event_btnEliminarProyeccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditarProyeccion;
    private javax.swing.JButton btnEliminarProyeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreLugarProd;
    private javax.swing.JLabel lblRegistroICA;
    private javax.swing.JTable tblEspeciesLP;
    // End of variables declaration//GEN-END:variables
}
