/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clases.libreria;

import Clases.vistas.GestionUsuarios;
import Clases.vistas.GestionRoles;
import Clases.vistas.GestionDepartamentos;
import Clases.vistas.GestionMunicipios;
import Clases.vistas.GestionVeredas;
import Clases.vistas.GestionLugaresProduccion;
import Clases.vistas.GestionPredios;
import Clases.vistas.GestionPlagas;
import Clases.vistas.GestionEspeciesVegetales;
import Clases.vistas.GestionVariedadEspecies;
import Clases.vistas.Principal;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.BorderLayout;
import javax.swing.*;
import javax.swing.JPanel;

/**
 *
 * @author ricar
 */
public class Dashboard extends javax.swing.JFrame {

    private String idUsuario;
    private String nombreUsuario;
    private String nombreRol;

    // Constructor con datos del usuario
    public Dashboard(String idUsuario, String nombreUsuario, String nombreRol) {
        this.idUsuario = idUsuario;
        this.nombreUsuario = nombreUsuario;
        this.nombreRol = nombreRol;

        initComponents();
        InitContent();
        configurarMenuSegunRol();
        setLocationRelativeTo(null);
    }

    /**
     * private static final java.util.logging.Logger logger =
     * java.util.logging.Logger.getLogger(Dashboard.class.getName()); Creates
     * new form Dashboard
     */
    public Dashboard() {
        initComponents();
        InitContent();
        setLocationRelativeTo(null);
    }

    private void InitContent() {
        ShowJPanel(new Principal());
    }

    public static void ShowJPanel(JPanel p) {
        p.setSize(750, 430);
        p.setLocation(0, 0);

        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /*ShowJPanel(new Principal());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        btnGestionRol = new javax.swing.JButton();
        btnGestionUsuario = new javax.swing.JButton();
        btnGestionMunicipio = new javax.swing.JButton();
        btnGestionarDepartamentos = new javax.swing.JButton();
        btnGestionVereda = new javax.swing.JButton();
        btnGestionPredio = new javax.swing.JButton();
        btnGestionLugarProd = new javax.swing.JButton();
        btnGestionLote = new javax.swing.JButton();
        btnGestionPlaga = new javax.swing.JButton();
        btnGestionEspecieVeg = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        logo = new javax.swing.JPanel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1032, 640));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(1032, 640));

        menu.setBackground(new java.awt.Color(27, 94, 32));
        menu.setPreferredSize(new java.awt.Dimension(270, 640));

        btnGestionRol.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionRol.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionRol.setText("Roles");
        btnGestionRol.setBorder(null);
        btnGestionRol.setBorderPainted(false);
        btnGestionRol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGestionRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionRolActionPerformed(evt);
            }
        });

        btnGestionUsuario.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionUsuario.setText("Usuarios");
        btnGestionUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGestionUsuario.setBorderPainted(false);
        btnGestionUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGestionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionUsuarioActionPerformed(evt);
            }
        });

        btnGestionMunicipio.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionMunicipio.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionMunicipio.setText("Municipio");
        btnGestionMunicipio.setBorder(null);
        btnGestionMunicipio.setBorderPainted(false);
        btnGestionMunicipio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGestionMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionMunicipioActionPerformed(evt);
            }
        });

        btnGestionarDepartamentos.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionarDepartamentos.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarDepartamentos.setText("Departamento");
        btnGestionarDepartamentos.setBorder(null);
        btnGestionarDepartamentos.setBorderPainted(false);
        btnGestionarDepartamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGestionarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarDepartamentosActionPerformed(evt);
            }
        });

        btnGestionVereda.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionVereda.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionVereda.setText("Vereda");
        btnGestionVereda.setBorder(null);
        btnGestionVereda.setBorderPainted(false);
        btnGestionVereda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGestionVereda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionVeredaActionPerformed(evt);
            }
        });

        btnGestionPredio.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionPredio.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionPredio.setText("Predio");
        btnGestionPredio.setBorder(null);
        btnGestionPredio.setBorderPainted(false);
        btnGestionPredio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionPredioActionPerformed(evt);
            }
        });

        btnGestionLugarProd.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionLugarProd.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionLugarProd.setText("Lugar de Producción");
        btnGestionLugarProd.setBorder(null);
        btnGestionLugarProd.setBorderPainted(false);
        btnGestionLugarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionLugarProdActionPerformed(evt);
            }
        });

        btnGestionLote.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionLote.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionLote.setText("Lote");
        btnGestionLote.setBorder(null);
        btnGestionLote.setBorderPainted(false);
        btnGestionLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionLoteActionPerformed(evt);
            }
        });

        btnGestionPlaga.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionPlaga.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionPlaga.setText("Especie Vegetal");
        btnGestionPlaga.setBorder(null);
        btnGestionPlaga.setBorderPainted(false);
        btnGestionPlaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionPlagaActionPerformed(evt);
            }
        });

        btnGestionEspecieVeg.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionEspecieVeg.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionEspecieVeg.setText("Variedad Especies Vegetales");
        btnGestionEspecieVeg.setAutoscrolls(true);
        btnGestionEspecieVeg.setBorder(null);
        btnGestionEspecieVeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionEspecieVegActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(27, 94, 32));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Plagas");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(27, 94, 32));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Inspeccion Fitosanitaria");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(27, 94, 32));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCerrarSesion.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionarDepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionVereda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionPredio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionLugarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionLote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionPlaga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionEspecieVeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(btnGestionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnGestionRol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnGestionarDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnGestionMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnGestionVereda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnGestionPredio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnGestionLugarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnGestionLote, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnGestionPlaga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnGestionEspecieVeg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        header.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Software de Gestión Agrícola");

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBienvenida.setText("Bienvenido: Usuario");

        lblRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRol.setText("Rol: ADMINISTRADOR");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(lblBienvenida)
                    .addComponent(lblRol))
                .addContainerGap(399, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRol)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        logo.setBackground(new java.awt.Color(27, 94, 32));
        logo.setPreferredSize(new java.awt.Dimension(270, 135));

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 750, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Control de visibilidad según Rol
    private void configurarMenuSegunRol() {
        lblBienvenida.setText("Bienvenido: " + nombreUsuario);
        lblRol.setText("Rol: " + nombreRol);

        switch (nombreRol) {
            case "Administrador ICA":
                break;
            case "Propietario":
                btnGestionMunicipio.setVisible(false);
                btnGestionUsuario.setVisible(false);
                btnGestionarDepartamentos.setVisible(false);
                break;
            case "Productor":
                btnGestionMunicipio.setVisible(false);
                btnGestionarDepartamentos.setVisible(false);
                btnGestionUsuario.setVisible(false);
                btnGestionVereda.setVisible(false);
                break;
            case "Asistente Técnico":
                btnGestionMunicipio.setVisible(false);
                btnGestionVereda.setVisible(false);
                btnGestionUsuario.setVisible(false);
                break;
        }
    }
    private void btnGestionarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarDepartamentosActionPerformed
        ShowJPanel(new GestionDepartamentos());         // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarDepartamentosActionPerformed

    private void btnGestionVeredaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionVeredaActionPerformed
         ShowJPanel(new GestionVeredas());
    }//GEN-LAST:event_btnGestionVeredaActionPerformed

    private void btnGestionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUsuarioActionPerformed
        ShowJPanel(new GestionUsuarios());        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionUsuarioActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Está seguro que desea cerrar sesión?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            this.dispose(); // Cerrar esta ventana
            FormLogin login = new FormLogin();
            login.setVisible(true); // Volver al login
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnGestionRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionRolActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new GestionRoles());
    }//GEN-LAST:event_btnGestionRolActionPerformed

    private void btnGestionMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionMunicipioActionPerformed
        ShowJPanel(new GestionMunicipios()); // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionMunicipioActionPerformed

    private void btnGestionPredioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionPredioActionPerformed
        ShowJPanel(new GestionPredios()); // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionPredioActionPerformed

    private void btnGestionLugarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionLugarProdActionPerformed
        ShowJPanel(new GestionLugaresProduccion()); // TODO add your handling code here:        // TODO add your handling code here:

    }//GEN-LAST:event_btnGestionLugarProdActionPerformed

    private void btnGestionLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionLoteActionPerformed
    }//GEN-LAST:event_btnGestionLoteActionPerformed

    private void btnGestionPlagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionPlagaActionPerformed
        ShowJPanel(new GestionEspeciesVegetales()); // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionPlagaActionPerformed

    private void btnGestionEspecieVegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEspecieVegActionPerformed
         ShowJPanel(new GestionVariedadEspecies()); // TODO add your handling code here:        // TODO add your handling code here:       // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionEspecieVegActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          ShowJPanel(new GestionPlagas()); // TODO add your handling code here:        // TODO add your handling code here:       // TODO add your handling code here:       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGestionEspecieVeg;
    private javax.swing.JButton btnGestionLote;
    private javax.swing.JButton btnGestionLugarProd;
    private javax.swing.JButton btnGestionMunicipio;
    private javax.swing.JButton btnGestionPlaga;
    private javax.swing.JButton btnGestionPredio;
    private javax.swing.JButton btnGestionRol;
    private javax.swing.JButton btnGestionUsuario;
    private javax.swing.JButton btnGestionVereda;
    private javax.swing.JButton btnGestionarDepartamentos;
    private static javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
