/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clases.libreria;

import Clases.vistas.GestionUsuarios;
import Clases.vistas.GestionRoles;
import Clases.vistas.GestionDepartamentos;
import Clases.vistas.GestionMunicipios;
import Clases.vistas.GestionVeredas;
import Clases.vistas.GestionLugaresProduccion;
import Clases.vistas.GestionPredios;
import Clases.vistas.GestionPlagas;
import Clases.vistas.GestionEspeciesVegetales;
import Clases.vistas.GestionVariedadEspecies;
import Clases.vistas.GestionLotes;
import Clases.vistas.GestionInspeccionesFitosanitarias;
import Clases.vistas.Principal;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.BorderLayout;
import javax.swing.*;
import javax.swing.JPanel;

/**
 *
 * @author ricar
 */
public class Dashboard extends javax.swing.JFrame {

    private String idUsuario;
    private String nombreUsuario;
    private String nombreRol;

    // Constructor con datos del usuario
    public Dashboard(String idUsuario, String nombreUsuario, String nombreRol) {
        this.idUsuario = idUsuario;
        this.nombreUsuario = nombreUsuario;
        this.nombreRol = nombreRol;

        initComponents();
        InitContent();
        configurarMenuSegunRol();
        setLocationRelativeTo(null);
    }

    /**
     * private static final java.util.logging.Logger logger =
     * java.util.logging.Logger.getLogger(Dashboard.class.getName()); Creates
     * new form Dashboard
     */
    public Dashboard() {
        initComponents();
        InitContent();
        setLocationRelativeTo(null);
    }

    private void InitContent() {
        ShowJPanel(new Principal());
    }

    public static void ShowJPanel(JPanel p) {
        p.setSize(770, 480);
        p.setLocation(0, 0);

        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /*ShowJPanel(new Principal());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        logo = new javax.swing.JPanel();
        btnMenuPrincipal = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menu = new javax.swing.JPanel();
        btnGestionLote = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnGestionEspecie = new javax.swing.JButton();
        jLabelInspec = new javax.swing.JLabel();
        btnGestionInspeccion = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        btnGestionVereda = new javax.swing.JButton();
        jLabelTerritorial = new javax.swing.JLabel();
        btnGestionLugarProd = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnGestionVariedad = new javax.swing.JButton();
        btnGestionarDepartamentos = new javax.swing.JButton();
        btnGestionMunicipio = new javax.swing.JButton();
        btnGestionPredio = new javax.swing.JButton();
        btnGestionPlaga = new javax.swing.JButton();
        jLabelCatalogos = new javax.swing.JLabel();
        jLabelUbicacion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnGestionRol = new javax.swing.JButton();
        btnGestionUsuario = new javax.swing.JButton();
        jLabelUsers = new javax.swing.JLabel();
        cerrarSesion = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1032, 640));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(1032, 640));

        header.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Software de Gestión Agrícola");

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBienvenida.setText("Bienvenido: Usuario");

        lblRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRol.setText("Rol: ADMINISTRADOR");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(lblBienvenida)
                    .addComponent(lblRol))
                .addContainerGap(396, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRol)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        logo.setBackground(new java.awt.Color(27, 94, 32));
        logo.setPreferredSize(new java.awt.Dimension(270, 135));

        btnMenuPrincipal.setBackground(new java.awt.Color(32, 108, 38));
        btnMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        btnMenuPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(27, 94, 32));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        menu.setBackground(new java.awt.Color(27, 94, 32));
        menu.setPreferredSize(new java.awt.Dimension(285, 562));

        btnGestionLote.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionLote.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionLote.setText("Lote");
        btnGestionLote.setBorder(null);
        btnGestionLote.setBorderPainted(false);
        btnGestionLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionLoteActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));

        btnGestionEspecie.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionEspecie.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionEspecie.setText("Especie Vegetal");
        btnGestionEspecie.setBorder(null);
        btnGestionEspecie.setBorderPainted(false);
        btnGestionEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionEspecieActionPerformed(evt);
            }
        });

        jLabelInspec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelInspec.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInspec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inspeccion.png"))); // NOI18N
        jLabelInspec.setText("Gestión de Inspecciones:");

        btnGestionInspeccion.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionInspeccion.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionInspeccion.setText("Inspeccion Fitosanitaria");
        btnGestionInspeccion.setBorder(null);
        btnGestionInspeccion.setBorderPainted(false);
        btnGestionInspeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionInspeccionActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));

        btnGestionVereda.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionVereda.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionVereda.setText("Vereda");
        btnGestionVereda.setBorder(null);
        btnGestionVereda.setBorderPainted(false);
        btnGestionVereda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGestionVereda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionVeredaActionPerformed(evt);
            }
        });

        jLabelTerritorial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTerritorial.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTerritorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lugar_lote.png"))); // NOI18N
        jLabelTerritorial.setText("Gestión Territorial:");

        btnGestionLugarProd.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionLugarProd.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionLugarProd.setText("Lugar de Producción");
        btnGestionLugarProd.setBorder(null);
        btnGestionLugarProd.setBorderPainted(false);
        btnGestionLugarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionLugarProdActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));

        btnGestionVariedad.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionVariedad.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionVariedad.setText("Variedad Especies Vegetales");
        btnGestionVariedad.setAutoscrolls(true);
        btnGestionVariedad.setBorder(null);
        btnGestionVariedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionVariedadActionPerformed(evt);
            }
        });

        btnGestionarDepartamentos.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionarDepartamentos.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarDepartamentos.setText("Departamento");
        btnGestionarDepartamentos.setBorder(null);
        btnGestionarDepartamentos.setBorderPainted(false);
        btnGestionarDepartamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGestionarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarDepartamentosActionPerformed(evt);
            }
        });

        btnGestionMunicipio.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionMunicipio.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionMunicipio.setText("Municipio");
        btnGestionMunicipio.setBorder(null);
        btnGestionMunicipio.setBorderPainted(false);
        btnGestionMunicipio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGestionMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionMunicipioActionPerformed(evt);
            }
        });

        btnGestionPredio.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionPredio.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionPredio.setText("Predio");
        btnGestionPredio.setBorder(null);
        btnGestionPredio.setBorderPainted(false);
        btnGestionPredio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionPredioActionPerformed(evt);
            }
        });

        btnGestionPlaga.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionPlaga.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionPlaga.setText("Plagas");
        btnGestionPlaga.setBorder(null);
        btnGestionPlaga.setBorderPainted(false);
        btnGestionPlaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionPlagaActionPerformed(evt);
            }
        });

        jLabelCatalogos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCatalogos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCatalogos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/catalogo.png"))); // NOI18N
        jLabelCatalogos.setText("Gestión de Catálogos:");

        jLabelUbicacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUbicacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUbicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ubicacion.png"))); // NOI18N
        jLabelUbicacion.setText("Gestión de Ubicación:");

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        btnGestionRol.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionRol.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionRol.setText("Roles");
        btnGestionRol.setBorder(null);
        btnGestionRol.setBorderPainted(false);
        btnGestionRol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGestionRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionRolActionPerformed(evt);
            }
        });

        btnGestionUsuario.setBackground(new java.awt.Color(27, 94, 32));
        btnGestionUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionUsuario.setText("Usuarios");
        btnGestionUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGestionUsuario.setBorderPainted(false);
        btnGestionUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGestionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionUsuarioActionPerformed(evt);
            }
        });

        jLabelUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUsers.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        jLabelUsers.setText("Gestión de Usuarios:");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGestionMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionarDepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionVereda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionPredio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionLugarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionLote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionEspecie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionVariedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionPlaga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionInspeccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator5)
                            .addComponent(jSeparator4))
                        .addContainerGap())
                    .addComponent(jLabelUsers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelUbicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTerritorial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCatalogos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelInspec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionRol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionarDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionVereda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTerritorial, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionPredio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionLugarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionLote, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCatalogos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionVariedad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionPlaga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInspec, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionInspeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(menu);

        cerrarSesion.setBackground(new java.awt.Color(27, 94, 32));

        btnCerrarSesion.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cerrarSesionLayout = new javax.swing.GroupLayout(cerrarSesion);
        cerrarSesion.setLayout(cerrarSesionLayout);
        cerrarSesionLayout.setHorizontalGroup(
            cerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cerrarSesionLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cerrarSesionLayout.setVerticalGroup(
            cerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cerrarSesionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(cerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Control de visibilidad según Rol
    private void configurarMenuSegunRol() {

        lblBienvenida.setText("Bienvenido: " + nombreUsuario);
        lblRol.setText("Rol: " + nombreRol);

        switch (nombreRol) {

            case "Administrador ICA":
                // Todo visible (o ajusta según necesites)
                break;

            case "Propietario":
                btnGestionRol.setVisible(false);
                btnGestionUsuario.setVisible(false);
                btnGestionarDepartamentos.setVisible(true);
                btnGestionMunicipio.setVisible(true);
                btnGestionVereda.setVisible(true);
                btnGestionPredio.setVisible(true);
                btnGestionLugarProd.setVisible(false);
                btnGestionLote.setVisible(false);
                btnGestionEspecie.setVisible(false);
                btnGestionVariedad.setVisible(false);
                btnGestionPlaga.setVisible(false);
                btnGestionInspeccion.setVisible(false);
                break;

            case "Productor":
                btnGestionRol.setVisible(false);
                btnGestionUsuario.setVisible(false);
                btnGestionarDepartamentos.setVisible(false);
                btnGestionMunicipio.setVisible(false);
                btnGestionVereda.setVisible(false);
                btnGestionPredio.setVisible(true);
                btnGestionLugarProd.setVisible(true);
                btnGestionLote.setVisible(true);
                btnGestionEspecie.setVisible(true);
                btnGestionVariedad.setVisible(true);
                btnGestionPlaga.setVisible(false);
                btnGestionInspeccion.setVisible(true);
                break;

            case "Asistente Tecnico":
                btnGestionRol.setVisible(false);
                btnGestionUsuario.setVisible(false);
                btnGestionarDepartamentos.setVisible(false);
                btnGestionMunicipio.setVisible(false);
                btnGestionVereda.setVisible(false);
                btnGestionPredio.setVisible(false);
                btnGestionLugarProd.setVisible(true);
                btnGestionLote.setVisible(true);
                btnGestionEspecie.setVisible(true);
                btnGestionVariedad.setVisible(true);
                btnGestionPlaga.setVisible(true);
                btnGestionInspeccion.setVisible(true);
                break;

            default:
                // Ocultar todo si el rol no existe
                btnGestionRol.setVisible(false);
                btnGestionUsuario.setVisible(false);
                btnGestionarDepartamentos.setVisible(false);
                btnGestionMunicipio.setVisible(false);
                btnGestionVereda.setVisible(false);
                btnGestionPredio.setVisible(false);
                btnGestionLugarProd.setVisible(false);
                btnGestionLote.setVisible(false);
                btnGestionEspecie.setVisible(false);
                btnGestionVariedad.setVisible(false);
                btnGestionPlaga.setVisible(false);
                btnGestionInspeccion.setVisible(false);

                // Indicar rol inexistente
                lblRol.setText("Rol: No tiene rol asignado");
                break;
        }
    }

    private void btnGestionarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarDepartamentosActionPerformed
        ShowJPanel(new GestionDepartamentos(nombreRol));         // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarDepartamentosActionPerformed

    private void btnGestionVeredaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionVeredaActionPerformed
        ShowJPanel(new GestionVeredas(nombreRol));
    }//GEN-LAST:event_btnGestionVeredaActionPerformed

    private void btnGestionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUsuarioActionPerformed
        ShowJPanel(new GestionUsuarios());        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionUsuarioActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Está seguro que desea cerrar sesión?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            this.dispose(); // Cerrar esta ventana
            FormLogin login = new FormLogin();
            login.setVisible(true); // Volver al login
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnGestionRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionRolActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new GestionRoles());
    }//GEN-LAST:event_btnGestionRolActionPerformed

    private void btnGestionMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionMunicipioActionPerformed
        ShowJPanel(new GestionMunicipios(nombreRol)); // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionMunicipioActionPerformed

    private void btnGestionPredioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionPredioActionPerformed
        ShowJPanel(new GestionPredios(nombreRol)); // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionPredioActionPerformed

    private void btnGestionLugarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionLugarProdActionPerformed
        ShowJPanel(new GestionLugaresProduccion(nombreRol)); // TODO add your handling code here:        // TODO add your handling code here:

    }//GEN-LAST:event_btnGestionLugarProdActionPerformed

    private void btnGestionLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionLoteActionPerformed
        ShowJPanel(new GestionLotes(nombreRol)); // TODO add your handling code here:        // TODO add your handling code here:
       }//GEN-LAST:event_btnGestionLoteActionPerformed

    private void btnGestionEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEspecieActionPerformed
        ShowJPanel(new GestionEspeciesVegetales(nombreRol)); // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionEspecieActionPerformed

    private void btnGestionVariedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionVariedadActionPerformed
        ShowJPanel(new GestionVariedadEspecies(nombreRol)); // TODO add your handling code here:        // TODO add your handling code here:       // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionVariedadActionPerformed

    private void btnGestionPlagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionPlagaActionPerformed
        ShowJPanel(new GestionPlagas(nombreRol)); // TODO add your handling code here:        // TODO add your handling code here:       // TODO add your handling code here:       // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionPlagaActionPerformed

    private void btnGestionInspeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionInspeccionActionPerformed
        ShowJPanel(new GestionInspeccionesFitosanitarias(nombreRol)); // TODO add your handling code here:        // TODO add your handling code here:       // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionInspeccionActionPerformed

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        ShowJPanel(new Principal());
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGestionEspecie;
    private javax.swing.JButton btnGestionInspeccion;
    private javax.swing.JButton btnGestionLote;
    private javax.swing.JButton btnGestionLugarProd;
    private javax.swing.JButton btnGestionMunicipio;
    private javax.swing.JButton btnGestionPlaga;
    private javax.swing.JButton btnGestionPredio;
    private javax.swing.JButton btnGestionRol;
    private javax.swing.JButton btnGestionUsuario;
    private javax.swing.JButton btnGestionVariedad;
    private javax.swing.JButton btnGestionVereda;
    private javax.swing.JButton btnGestionarDepartamentos;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JPanel cerrarSesion;
    private static javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabelCatalogos;
    private javax.swing.JLabel jLabelInspec;
    private javax.swing.JLabel jLabelTerritorial;
    private javax.swing.JLabel jLabelUbicacion;
    private javax.swing.JLabel jLabelUsers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
